"""Value-only content operations supplied to document scenarios."""

from collections.abc import Mapping
from typing import Any, Protocol


class DocumentContent(Protocol):
    def prompt_descriptor(self, job_type: str) -> Mapping[str, Any] | None: ...
    def render_document_ast(self, document: Mapping[str, Any]) -> str: ...
    def validate_contract(self, name: str, value: object) -> None: ...
    def apply_change_plan(self, base: Mapping[str, Any], plan: Mapping[str, Any]) -> dict[str, Any]: ...
    def validate_document_ast(self, value: object) -> dict[str, Any]: ...
    def published_template(self) -> Mapping[str, Any]: ...
